# Site Data
title: "t3rb3d's blog"
tagline: " — a Digital Garden 🌱"
name: "Dániel Terbe"
author_bio:
  "Hey there! 👋 I'm Daniel, a Budapest-based researcher and developer in the field of AI and Machine Learning, recently venturing into the world of financial trading.   
   Dive into my blog posts where we unravel the intricacies of different ML methods.
   Eager to hear your thoughts – join the conversation in the comments and let's build a thriving community!"
description: "A Digital Garden: Capturing my daily thoughts and progress, as well as curated ideas, reviews and articles."
footer_description:
  'The phrase "digital garden" is a metaphor for thinking, writing and creating that focuses less on the
  outcome and more on the process, care, and craft it takes to get there.
  Like gardeners planting seeds and tending the soil, we toil and turn the earth; though blooms may come in their own time, they cannot be rushed or forced.'
notes_url: "https://terbe.dev/notes/"
profile_pic: "https://avatars.githubusercontent.com/u/13771341?s=400&v=4"
favicon: /assets/img/favicon.png
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://terbe.dev" # the base hostname & protocol for your site, e.g. https://example.com
theme_color: white
encoding: utf-8

# Links and Social Media
donate_link: https://ko-fi.com/t3rb3d
repository: https://github.com/terbed/blog
github: https://github.com/terbed
twitter: https://twitter.com/t3rb3d4
#portfolio: https://brennanbrown.ca
email: terbed@gmail.com

# Build Settings
theme: null
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-minifier
  - jekyll-toc
  - jekyll-katex

markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false
  math_engine: mathjax
#  math_engine: katex
  smart_quotes: ["apos", "apos", "quot", "quot"]
  syntax_highlighter: rouge

#katex:
#  js_path: "assets"  # Path used to search for katex.min.js
#  rendering_options:
#    # Default KaTeX rendering options. See https://github.com/Khan/KaTeX#rendering-options
#    throw_error: false      # throwOnError - set to false if you want rendering to output error as text rather than a build error
#    error_color: "#cc0000"  # errorColor

sass:
  style: compressed

JEKYLL_ENV: "production"

collections:
  notes:
    output: true
    permalink: /notes/:title
  journals:
    output: true
    permalink: /journals/:title
  pages:
    output: true
    permalink: /page/:name

disqus:
  shortname: t3rb3ds-blog

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /posts/:title
      content-type: post
      category: "Post"
      toc: true
  - scope:
      path: ""
      type: notes
    values:
      layout: post
      content-type: notes
  - scope:
      path: ""
      type: journals
    values:
      layout: post
      content-type: journals
  - scope:
      path: ""
      type: pages
    values:
      layout: page
      content-type: pages

jekyll-archives:
  enabled: []
  layout: default
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"

toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no-toc
  list_class: section-nav
  sublist_class: ""
  item_class: entry
  item_prefix: toc-